development: &default		
  adapter: postgresql		
  encoding: unicode		
  host: <%= ENV["LG_HOST"] %>
  port: 5432		
  database: <%= ENV["LG_DATABASE"] %>
  pool: 5		
  username: <%= ENV["LG_USER"] %>
  password: <%= ENV["LG_PASSWORD"] %>
  reconnect: true		

staging: 		
  <<: *default		

test:		
  <<: *default  

production:		
  <<: *default 		