

development: &default
  adapter: postgresql
  encoding: unicode
  host: lr-staging2.c3n3fi9grsp4.us-west-2.rds.amazonaws.com
  port: 5432
  database: logging_rocks
  pool: 5
  username: rundong
  password: ^sCF.dFzA3`a!@r`
  reconnect: true

staging: 
  <<: *default

test:
  <<: *default

production:
  <<: *default